backend:
  name: git-gateway
  repo: brunospitti/bruno-spitti-com
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "generalInfo"
    label: "General Info"
    folder: "src/info/generalInfo"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "generalInfo",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Main Tech", name: "mainTech", widget: "list" }
      - { label: "Section titles", name: "sectiontitles", widget: "list" }
      - { label: "Hello", name: "hello", widget: "text" }
      - { label: "Projects", name: "projects", widget: "text" }
      - { label: "Contact", name: "contact", widget: "text" }
      - {
          label: "Contact Info Titles",
          name: "contactIntoTitles",
          widget: "list",
        }
      - { label: "Contact Info Info", name: "contactIntoInfo", widget: "list" }
      - { label: "Contact Info URL", name: "contactIntoURL", widget: "list" }

  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project",
        }
      - { label: "Index", name: "index", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Brief Description",
          name: "brief_description",
          widget: "text",
        }
      - {
          label: "Screenshot",
          name: "screenshot",
          widget: "image",
          required: false,
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "What I learned", name: "what_i_learned", widget: "text" }
      - { label: "Technologies used", name: "technologies", widget: "list" }
      - {
          label: "Check yourself live URL",
          name: "live_url",
          widget: "string",
          required: false,
        }
      - {
          label: "Check yourself github URL",
          name: "github_url",
          widget: "string",
          required: false,
        }

  - name: "workExperience"
    label: "Work Experience"
    folder: "src/info/workExperience"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "workExperience",
        }
      - { label: "Index", name: "index", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Period", name: "period", widget: "string" }
      - {
          label: "Brief Description",
          name: "brief_description",
          widget: "text",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Technologies used", name: "technologies", widget: "list" }
